### PR TITLE
WineD3D 2.4

### PR DESCRIPTION
**Pull request by Svyatpro**
Will it be rebased according to WineD3D 2.4 Staging?

### CODE REVIEW

**Comment by gamax92** [comment]
Why did you open a PR from my fork to here ...

**Comment by Svyatpro** [comment]
Sorry, I didn't know.

**Comment by slackner** [comment]
Although some of the changes by Andrew Wesie and @gamax92 might be suitable for Wine Staging, this repository certainly isn't the correct place to suggest them for inclusion. All content in this repository is generated automatically. The correct way is to split the changes into separate patches and then open patch submission requests at https://dev.wine-staging.com/. Also please note that Wine rules require that patches give attribution to the original authors and include real names.

**Comment by gamax92** [comment]
It's up to Andrew if he wants to add the various changes into wine/wine-staging. While I've made my various changes to these patches it's all based on his work.

**Comment by mmueller2012** [comment]
Technically, this would not be a problem. The Signed-off-by system used by Wine allows multiple authors to work on a patch or to send patches created by someone else.

**Pull request closed without merging**
