### PR TITLE
Correct DDSCAPS2 and DDSURFACEDESC2 structures and their uses.

### PR DESCRIPTION
**Pull request by AmineKhaldi**

### CODE REVIEW

**Comment by slackner** [comment]
Doesn't compile here, gcc 4.9.2 is complaining with a lot of messages like:

```
device.c: In function 'd3d_device_update_depth_stencil':
device.c:6750:5: error: missing braces around initializer [-Werror=missing-braces]
     static DDSCAPS2 depthcaps = { DDSCAPS_ZBUFFER, 0, 0, 0 };
     ^
device.c:6750:5: error: (near initialization for 'depthcaps.u1') [-Werror=missing-braces]
```

Adding braces around the union argument seems to fix it here. Does that also work on older compilers / MSVC ?

**Comment by AmineKhaldi** [comment]
That looks like -Werror which I don't use, so I get these as warnings.
I didn't want to add the missing braces fixes to this patch because it already went beyond one module. I wanted to send other pull requests about them, one for each module. Should I add them here instead?

**Comment by slackner** [comment]
Yes, please add them to this patch. Its better to avoid introducing warnings, even if it makes the patch much bigger.

**Comment by AmineKhaldi** [comment]
Please check now.

**Comment by slackner** [comment]
It was still missing at a couple of places in the ddraw tests. I have fixed that and added the patch, thanks ;)

https://github.com/wine-compholio/wine-staging/commit/3efff4cb883d9b168691f2e8c60e2be1303c1550

**Pull request closed without merging**
